### PR TITLE
Timeout for change material wizard

### PR DESCRIPTION
**Pull request by TinkerGnome**
- add a timeout for the change material wizard
- after 2 minutes without user interaction switch the heater off and return to main menu

see feature request:
https://ultimaker.com/en/community/view/11267-um2-timeout-of-change-material-procedure-request

### CODE REVIEW

**Comment by TinkerGnome** [comment]
Only the first commit is relevant for this request,
Sorry, i (again) used the wrong branch for the other commits... and no clue about a way to revert this...

**Comment by daid** [comment]
I think git handles the extra commits quite fine (else it should show a merge conflict)

However, I think these changes will cause issues if you use the change material during a pause of a print, then the timeout will send you back to the main menu, which isn't the proper menu to return to then.

**Comment by TinkerGnome** [comment]
good point... that would be... not funny  ;-)
I think i should withdraw this and make some refinements first....
See you later!

**Comment by daid** [comment]
But, thinking along that line, few more things that could use sort of timeouts. For example, pause print could cool the head off after a time-out. But then it does need to heat it back up when you want to continue the print. So that's quite some extra housekeeping to do...

**Comment by TinkerGnome** [comment]
Yep, i agree, that's where it ends up...
I'm confident - many hands make light work.... ;-)
Let's see...

**Comment by Cederb** [comment]
It would need careful consideration to not break anything else, but timeouts would greatly enhance the user experience since there would be less possibllity to forget the printer and have material carbonizing in the nozzle :-)

**Comment by TinkerGnome** [comment]
daid said:
> But, thinking along that line, few more things that could use sort of timeouts
> ...
> But then it does need to heat it back up

I reorganized some things this weekend to follow this approach. The timeout check will be always active, except during sd printing or an active serial connection. After resuming a paused print and during material change (insert or remove) there's an upstream heatup stage if necessary. The user interface stays at the current menu after heatup - no undesired menu navigation. The latter has one exception (so far) - i think, the "Move material" menu should be canceled after a timeout and return to "Maintenance Advanced" (it's pretty useless with a cold nozzle).

@Cederb: i suggest a timeout period of 3 minutes - would this be a good choice / compromise?
@daid: Could this be a way to go? And what about the time span? Or would you even like to make it configurable?

**Comment by Cederb** [comment]
@TinkerGnome: Yeah, 3min sounds like a good compromise.

**Pull request closed without merging**
